SERVER_URL_PREFIX=""
SERVER_HOSTNAME="localhost"
SERVER_JWT_EXPIRATION="1w"

APP_PATH="app"



DB_USER="app"
DB_PASS="HOLYCHICKEN"
DB_NAME="app_db"
DB_HOSTNAME="localhost"
DB_PORT="7377"


DB_PROTOCOL="couchdb"
COUCHDB_USER=$DB_USER
COUCHDB_PASSWORD=$DB_PASS
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$DB_PASS


DB_URL="${DB_PROTOCOL}://${DB_USER}:${DB_PASS}@${DB_HOSTNAME}:${DB_PORT}"