SERVER_URL_PREFIX=""
SERVER_HOSTNAME="localhost"
SERVER_JWT_EXPIRATION="1w"

APP_PATH="app"


DB_USER="app"
DB_PASS="HOLYCHICKEN"
DB_NAME="app_db"
DB_HOST="localhost:7377"


DB_PROTOCOL="http"
COUCHDB_USER=$DB_USER
COUCHDB_PASSWORD=$DB_PASS
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$DB_PASS


DB_URL="${DB_PROTOCOL}://${DB_USER}:${DB_PASS}@${DB_HOST}"